x-common-env: &cenv
  MEILI_URL: http://search:7700
  MEILI_MASTER_KEY: "$MEILI_MASTER_KEY"
  ORIGIN: "https://$WANDERER_HOST"
services:
  search:
    image: getmeili/meilisearch:v1.11.3
    environment:
      <<: *cenv
      MEILI_NO_ANALYTICS: "true"
    networks:
      - wanderer
    volumes:
      - ./data/data.ms:/meili_data/data.ms
    restart: unless-stopped
    healthcheck:
      test: curl --fail http://localhost:7700/health || exit 1
      interval: 15s
      retries: 10
      start_period: 20s
      timeout: 10s
  wanderer-db:
    image: flomp/wanderer-db
    depends_on:
      search:
        condition: service_healthy
    environment:
      <<: *cenv
      POCKETBASE_ENCRYPTION_KEY: "$POCKETBASE_KEY"
    networks:
      - wanderer
      - public20
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.wandererdb.rule=Host(`$WANDERER_DB_HOST`)
      - traefik.docker.network=public20
    volumes:
      - ./data/pb_data:/pb_data
    healthcheck:
      test: wget --spider -q http://localhost:8090/health || exit 1
      interval: 15s
      retries: 10
      start_period: 20s
      timeout: 10s
  web:
    image: flomp/wanderer-web
    depends_on:
      search:
        condition: service_healthy
      wanderer-db:
        condition: service_healthy
    environment:
      <<: *cenv
      BODY_SIZE_LIMIT: Infinity
      PUBLIC_POCKETBASE_URL: http://wanderer-db:8090
      PUBLIC_DISABLE_SIGNUP: "false"
      UPLOAD_FOLDER: /app/uploads
      UPLOAD_USER: null
      UPLOAD_PASSWORD: null
      PUBLIC_OVERPASS_API_URL: https://overpass-api.de
      PUBLIC_BROUTER_URL: https://$WANDERER_BROUTER_HOST
      PUBLIC_VALHALLA_URL: http://valhalla:8002
      PUBLIC_NOMINATIM_URL: https://nominatim.openstreetmap.org
    volumes:
      - ./data/uploads:/app/uploads
    networks:
      - wanderer
      - public20
    restart: unless-stopped
    healthcheck:
      test: curl --fail http://localhost:3000/ || exit 1
      interval: 15s
      retries: 10
      start_period: 20s
      timeout: 10s
    labels:
      - traefik.enable=true
      - traefik.http.routers.wanderer.rule=Host(`$WANDERER_HOST`)
      - traefik.docker.network=public20
  valhalla:
    image: ghcr.io/valhalla/valhalla-scripted:latest
    volumes:
      - ./data/valhalla:/custom_files
    environment:
      - tile_urls=https://download.geofabrik.de/europe/germany/niedersachsen-latest.osm.pbf
      - use_tiles_ignore_pbf=True
      - force_rebuild=False
      - force_rebuild_elevation=False
      - build_elevation=True
      - build_admins=True
      - build_time_zones=True
    networks:
      - wanderer
  brouter:
    image: ghcr.io/abrensch/brouter:v1.7.8
    volumes:
      - ./brouter-segments:/segments4
      - ./brouter-profiles:/profiles
    networks:
      - public20
    labels:
      - traefik.enable=true
      - traefik.http.routers.brouter.rule=Host(`$WANDERER_BROUTER_HOST`)
      - traefik.http.routers.brouter.service=brouter
      - traefik.http.services.brouter.loadbalancer.server.port=17777
networks:
  wanderer: null
  public20:
    external: true
